package modelo;
// Generated 16/06/2013 11:05:40 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Logradouros generated by hbm2java
 */
public class Logradouros  implements java.io.Serializable {


     private int cdLogradouro;
     private Bairros bairros;
     private String dsLogradouroNome;
     private String noLogradouroCep;
     private int cdTipoLogradouros;
     private Set tbEnderecos = new HashSet(0);

    public Logradouros() {
    }

	
    public Logradouros(int cdLogradouro, Bairros bairros, String dsLogradouroNome, String noLogradouroCep, int cdTipoLogradouros) {
        this.cdLogradouro = cdLogradouro;
        this.bairros = bairros;
        this.dsLogradouroNome = dsLogradouroNome;
        this.noLogradouroCep = noLogradouroCep;
        this.cdTipoLogradouros = cdTipoLogradouros;
    }
    public Logradouros(int cdLogradouro, Bairros bairros, String dsLogradouroNome, String noLogradouroCep, int cdTipoLogradouros, Set tbEnderecos) {
       this.cdLogradouro = cdLogradouro;
       this.bairros = bairros;
       this.dsLogradouroNome = dsLogradouroNome;
       this.noLogradouroCep = noLogradouroCep;
       this.cdTipoLogradouros = cdTipoLogradouros;
       this.tbEnderecos = tbEnderecos;
    }
   
    public int getCdLogradouro() {
        return this.cdLogradouro;
    }
    
    public void setCdLogradouro(int cdLogradouro) {
        this.cdLogradouro = cdLogradouro;
    }
    public Bairros getBairros() {
        return this.bairros;
    }
    
    public void setBairros(Bairros bairros) {
        this.bairros = bairros;
    }
    public String getDsLogradouroNome() {
        return this.dsLogradouroNome;
    }
    
    public void setDsLogradouroNome(String dsLogradouroNome) {
        this.dsLogradouroNome = dsLogradouroNome;
    }
    public String getNoLogradouroCep() {
        return this.noLogradouroCep;
    }
    
    public void setNoLogradouroCep(String noLogradouroCep) {
        this.noLogradouroCep = noLogradouroCep;
    }
    public int getCdTipoLogradouros() {
        return this.cdTipoLogradouros;
    }
    
    public void setCdTipoLogradouros(int cdTipoLogradouros) {
        this.cdTipoLogradouros = cdTipoLogradouros;
    }
    public Set getTbEnderecos() {
        return this.tbEnderecos;
    }
    
    public void setTbEnderecos(Set tbEnderecos) {
        this.tbEnderecos = tbEnderecos;
    }




}


