package modelo;
// Generated 16/06/2013 11:05:40 by Hibernate Tools 3.2.1.GA



/**
 * RlItemVenda generated by hbm2java
 */
public class RlItemVenda  implements java.io.Serializable {


     private Integer idItemVenda;
     private TbVenda tbVenda;
     private TbProduto tbProduto;
     private int quantidade;
     private double precoTotal;

    public RlItemVenda() {
    }

    public RlItemVenda(TbVenda tbVenda, TbProduto tbProduto, int quantidade, double precoTotal) {
       this.tbVenda = tbVenda;
       this.tbProduto = tbProduto;
       this.quantidade = quantidade;
       this.precoTotal = precoTotal;
    }
   
    public Integer getIdItemVenda() {
        return this.idItemVenda;
    }
    
    public void setIdItemVenda(Integer idItemVenda) {
        this.idItemVenda = idItemVenda;
    }
    public TbVenda getTbVenda() {
        return this.tbVenda;
    }
    
    public void setTbVenda(TbVenda tbVenda) {
        this.tbVenda = tbVenda;
    }
    public TbProduto getTbProduto() {
        return this.tbProduto;
    }
    
    public void setTbProduto(TbProduto tbProduto) {
        this.tbProduto = tbProduto;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public double getPrecoTotal() {
        return this.precoTotal;
    }
    
    public void setPrecoTotal(double precoTotal) {
        this.precoTotal = precoTotal;
    }




}


