package modelo;
// Generated 16/06/2013 11:05:40 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TbCliente generated by hbm2java
 */
public class TbCliente  implements java.io.Serializable {


     private Integer idCliente;
     private TbPessoa tbPessoa;
     private Set tbVendas = new HashSet(0);

    public TbCliente() {
    }

	
    public TbCliente(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }
    public TbCliente(TbPessoa tbPessoa, Set tbVendas) {
       this.tbPessoa = tbPessoa;
       this.tbVendas = tbVendas;
    }
   
    public Integer getIdCliente() {
        return this.idCliente;
    }
    
    public void setIdCliente(Integer idCliente) {
        this.idCliente = idCliente;
    }
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }
    public Set getTbVendas() {
        return this.tbVendas;
    }
    
    public void setTbVendas(Set tbVendas) {
        this.tbVendas = tbVendas;
    }




}


