package modelo;
// Generated 16/06/2013 11:05:40 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TbDepartamento generated by hbm2java
 */
public class TbDepartamento  implements java.io.Serializable {


     private Integer idDepartamento;
     private String departamento;
     private Set tbProdutos = new HashSet(0);

    public TbDepartamento() {
    }

	
    public TbDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public TbDepartamento(String departamento, Set tbProdutos) {
       this.departamento = departamento;
       this.tbProdutos = tbProdutos;
    }
   
    public Integer getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(Integer idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public Set getTbProdutos() {
        return this.tbProdutos;
    }
    
    public void setTbProdutos(Set tbProdutos) {
        this.tbProdutos = tbProdutos;
    }




}


