package modelo;
// Generated 16/06/2013 11:05:40 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TbEndereco generated by hbm2java
 */
public class TbEndereco  implements java.io.Serializable {


     private Integer idtbEndereco;
     private TbTipocomplemento tbTipocomplemento;
     private Logradouros logradouros;
     private String numero;
     private Set tbPessoas = new HashSet(0);

    public TbEndereco() {
    }

	
    public TbEndereco(TbTipocomplemento tbTipocomplemento, Logradouros logradouros, String numero) {
        this.tbTipocomplemento = tbTipocomplemento;
        this.logradouros = logradouros;
        this.numero = numero;
    }
    public TbEndereco(TbTipocomplemento tbTipocomplemento, Logradouros logradouros, String numero, Set tbPessoas) {
       this.tbTipocomplemento = tbTipocomplemento;
       this.logradouros = logradouros;
       this.numero = numero;
       this.tbPessoas = tbPessoas;
    }
   
    public Integer getIdtbEndereco() {
        return this.idtbEndereco;
    }
    
    public void setIdtbEndereco(Integer idtbEndereco) {
        this.idtbEndereco = idtbEndereco;
    }
    public TbTipocomplemento getTbTipocomplemento() {
        return this.tbTipocomplemento;
    }
    
    public void setTbTipocomplemento(TbTipocomplemento tbTipocomplemento) {
        this.tbTipocomplemento = tbTipocomplemento;
    }
    public Logradouros getLogradouros() {
        return this.logradouros;
    }
    
    public void setLogradouros(Logradouros logradouros) {
        this.logradouros = logradouros;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public Set getTbPessoas() {
        return this.tbPessoas;
    }
    
    public void setTbPessoas(Set tbPessoas) {
        this.tbPessoas = tbPessoas;
    }




}


