package modelo;
// Generated 16/06/2013 11:05:40 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TbFuncionario generated by hbm2java
 */
public class TbFuncionario  implements java.io.Serializable {


     private Integer idFuncionario;
     private TbTipofuncionario tbTipofuncionario;
     private TbPessoa tbPessoa;
     private Set tbVendas = new HashSet(0);
     private Set tbLogins = new HashSet(0);

    public TbFuncionario() {
    }

	
    public TbFuncionario(TbTipofuncionario tbTipofuncionario, TbPessoa tbPessoa) {
        this.tbTipofuncionario = tbTipofuncionario;
        this.tbPessoa = tbPessoa;
    }
    public TbFuncionario(TbTipofuncionario tbTipofuncionario, TbPessoa tbPessoa, Set tbVendas, Set tbLogins) {
       this.tbTipofuncionario = tbTipofuncionario;
       this.tbPessoa = tbPessoa;
       this.tbVendas = tbVendas;
       this.tbLogins = tbLogins;
    }
   
    public Integer getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(Integer idFuncionario) {
        this.idFuncionario = idFuncionario;
    }
    public TbTipofuncionario getTbTipofuncionario() {
        return this.tbTipofuncionario;
    }
    
    public void setTbTipofuncionario(TbTipofuncionario tbTipofuncionario) {
        this.tbTipofuncionario = tbTipofuncionario;
    }
    public TbPessoa getTbPessoa() {
        return this.tbPessoa;
    }
    
    public void setTbPessoa(TbPessoa tbPessoa) {
        this.tbPessoa = tbPessoa;
    }
    public Set getTbVendas() {
        return this.tbVendas;
    }
    
    public void setTbVendas(Set tbVendas) {
        this.tbVendas = tbVendas;
    }
    public Set getTbLogins() {
        return this.tbLogins;
    }
    
    public void setTbLogins(Set tbLogins) {
        this.tbLogins = tbLogins;
    }




}


