package modelo;
// Generated 16/06/2013 11:05:40 by Hibernate Tools 3.2.1.GA



/**
 * TbLogin generated by hbm2java
 */
public class TbLogin  implements java.io.Serializable {


     private Integer idUsuario;
     private TbFuncionario tbFuncionario;
     private String usuario;
     private String senha;

    public TbLogin() {
    }

    public TbLogin(TbFuncionario tbFuncionario, String usuario, String senha) {
       this.tbFuncionario = tbFuncionario;
       this.usuario = usuario;
       this.senha = senha;
    }
   
    public Integer getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Integer idUsuario) {
        this.idUsuario = idUsuario;
    }
    public TbFuncionario getTbFuncionario() {
        return this.tbFuncionario;
    }
    
    public void setTbFuncionario(TbFuncionario tbFuncionario) {
        this.tbFuncionario = tbFuncionario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }




}


