package modelo;
// Generated 16/06/2013 11:05:40 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TbPessoa generated by hbm2java
 */
public class TbPessoa  implements java.io.Serializable {


     private Integer idPessoa;
     private TbEndereco tbEndereco;
     private String nomePessoa;
     private String cpf;
     private String email;
     private Set tbFuncionarios = new HashSet(0);
     private Set tbTelefones = new HashSet(0);
     private Set tbClientes = new HashSet(0);

    public TbPessoa() {
    }

	
    public TbPessoa(TbEndereco tbEndereco, String nomePessoa, String cpf, String email) {
        this.tbEndereco = tbEndereco;
        this.nomePessoa = nomePessoa;
        this.cpf = cpf;
        this.email = email;
    }
    public TbPessoa(TbEndereco tbEndereco, String nomePessoa, String cpf, String email, Set tbFuncionarios, Set tbTelefones, Set tbClientes) {
       this.tbEndereco = tbEndereco;
       this.nomePessoa = nomePessoa;
       this.cpf = cpf;
       this.email = email;
       this.tbFuncionarios = tbFuncionarios;
       this.tbTelefones = tbTelefones;
       this.tbClientes = tbClientes;
    }
   
    public Integer getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(Integer idPessoa) {
        this.idPessoa = idPessoa;
    }
    public TbEndereco getTbEndereco() {
        return this.tbEndereco;
    }
    
    public void setTbEndereco(TbEndereco tbEndereco) {
        this.tbEndereco = tbEndereco;
    }
    public String getNomePessoa() {
        return this.nomePessoa;
    }
    
    public void setNomePessoa(String nomePessoa) {
        this.nomePessoa = nomePessoa;
    }
    public String getCpf() {
        return this.cpf;
    }
    
    public void setCpf(String cpf) {
        this.cpf = cpf;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Set getTbFuncionarios() {
        return this.tbFuncionarios;
    }
    
    public void setTbFuncionarios(Set tbFuncionarios) {
        this.tbFuncionarios = tbFuncionarios;
    }
    public Set getTbTelefones() {
        return this.tbTelefones;
    }
    
    public void setTbTelefones(Set tbTelefones) {
        this.tbTelefones = tbTelefones;
    }
    public Set getTbClientes() {
        return this.tbClientes;
    }
    
    public void setTbClientes(Set tbClientes) {
        this.tbClientes = tbClientes;
    }




}


