package modelo;
// Generated 16/06/2013 11:05:40 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TbProduto generated by hbm2java
 */
public class TbProduto  implements java.io.Serializable {


     private String idProduto;
     private TbDepartamento tbDepartamento;
     private String produto;
     private double valor;
     private int quantidade;
     private Set rlItemVendas = new HashSet(0);

    public TbProduto() {
    }

	
    public TbProduto(String idProduto, TbDepartamento tbDepartamento, String produto, double valor, int quantidade) {
        this.idProduto = idProduto;
        this.tbDepartamento = tbDepartamento;
        this.produto = produto;
        this.valor = valor;
        this.quantidade = quantidade;
    }
    public TbProduto(String idProduto, TbDepartamento tbDepartamento, String produto, double valor, int quantidade, Set rlItemVendas) {
       this.idProduto = idProduto;
       this.tbDepartamento = tbDepartamento;
       this.produto = produto;
       this.valor = valor;
       this.quantidade = quantidade;
       this.rlItemVendas = rlItemVendas;
    }
   
    public String getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(String idProduto) {
        this.idProduto = idProduto;
    }
    public TbDepartamento getTbDepartamento() {
        return this.tbDepartamento;
    }
    
    public void setTbDepartamento(TbDepartamento tbDepartamento) {
        this.tbDepartamento = tbDepartamento;
    }
    public String getProduto() {
        return this.produto;
    }
    
    public void setProduto(String produto) {
        this.produto = produto;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public int getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(int quantidade) {
        this.quantidade = quantidade;
    }
    public Set getRlItemVendas() {
        return this.rlItemVendas;
    }
    
    public void setRlItemVendas(Set rlItemVendas) {
        this.rlItemVendas = rlItemVendas;
    }




}


