package modelo;
// Generated 16/06/2013 11:05:40 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TbTipofuncionario generated by hbm2java
 */
public class TbTipofuncionario  implements java.io.Serializable {


     private Integer idTipoFuncionario;
     private String tipoFuncionario;
     private Set tbFuncionarios = new HashSet(0);

    public TbTipofuncionario() {
    }

	
    public TbTipofuncionario(String tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }
    public TbTipofuncionario(String tipoFuncionario, Set tbFuncionarios) {
       this.tipoFuncionario = tipoFuncionario;
       this.tbFuncionarios = tbFuncionarios;
    }
   
    public Integer getIdTipoFuncionario() {
        return this.idTipoFuncionario;
    }
    
    public void setIdTipoFuncionario(Integer idTipoFuncionario) {
        this.idTipoFuncionario = idTipoFuncionario;
    }
    public String getTipoFuncionario() {
        return this.tipoFuncionario;
    }
    
    public void setTipoFuncionario(String tipoFuncionario) {
        this.tipoFuncionario = tipoFuncionario;
    }
    public Set getTbFuncionarios() {
        return this.tbFuncionarios;
    }
    
    public void setTbFuncionarios(Set tbFuncionarios) {
        this.tbFuncionarios = tbFuncionarios;
    }




}


