package modelo;
// Generated 16/06/2013 11:05:40 by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TbVenda generated by hbm2java
 */
public class TbVenda  implements java.io.Serializable {


     private Integer idVenda;
     private TbFuncionario tbFuncionario;
     private TbCliente tbCliente;
     private String dataVenda;
     private Double valorVenda;
     private Set rlItemVendas = new HashSet(0);

    public TbVenda() {
    }

	
    public TbVenda(TbFuncionario tbFuncionario, String dataVenda) {
        this.tbFuncionario = tbFuncionario;
        this.dataVenda = dataVenda;
    }
    public TbVenda(TbFuncionario tbFuncionario, TbCliente tbCliente, String dataVenda, Double valorVenda, Set rlItemVendas) {
       this.tbFuncionario = tbFuncionario;
       this.tbCliente = tbCliente;
       this.dataVenda = dataVenda;
       this.valorVenda = valorVenda;
       this.rlItemVendas = rlItemVendas;
    }
   
    public Integer getIdVenda() {
        return this.idVenda;
    }
    
    public void setIdVenda(Integer idVenda) {
        this.idVenda = idVenda;
    }
    public TbFuncionario getTbFuncionario() {
        return this.tbFuncionario;
    }
    
    public void setTbFuncionario(TbFuncionario tbFuncionario) {
        this.tbFuncionario = tbFuncionario;
    }
    public TbCliente getTbCliente() {
        return this.tbCliente;
    }
    
    public void setTbCliente(TbCliente tbCliente) {
        this.tbCliente = tbCliente;
    }
    public String getDataVenda() {
        return this.dataVenda;
    }
    
    public void setDataVenda(String dataVenda) {
        this.dataVenda = dataVenda;
    }
    public Double getValorVenda() {
        return this.valorVenda;
    }
    
    public void setValorVenda(Double valorVenda) {
        this.valorVenda = valorVenda;
    }
    public Set getRlItemVendas() {
        return this.rlItemVendas;
    }
    
    public void setRlItemVendas(Set rlItemVendas) {
        this.rlItemVendas = rlItemVendas;
    }




}


